/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mpc.project;

import mpc.project.util.MathUtility;
import org.junit.Test;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.Random;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testApp() {
        System.out.println("Test");
    }
}
